database:
   kingdoms:
      host:
      database:
      username:
      password:
   website:
      host:
      database:
      username:
      password:
settings:
   promote-command: pex group <group> user add <user>
   