name: QuartzKingdoms
version: 1.0.0
author: The QuartzCraft Team! SoulPunisher, mba2012 and nfell2009!
website: http://www.quartzcraft.co.uk/
main: uk.co.quartzcraft.kingdoms.QuartzKingdoms
softdepend: [QuartzCore]

commands:
   quartzking:
      description: Runs quick checks.
      usage: /quartzking
      permission: QCK.quartzKing
      default: op
      permission-message: Unknown Command. Visit the QuartzCraft Wiki for help.
   kingdom:
      description: Main kingdoms command.
      usage: /kingdom
      permission: QCK.Kingdom
      default: false
      permission-message: Unknown Command. Visit the QuartzCraft Wiki for help.
      alias: king, k
Permissions:
   QCK.kingdom.*:
      description: Allows access to all QCK permissions.
      default: op
      children:
         QCK.Kingdom.info: true
         QCK.Kingdom.create: true
         QCK.Kingdom.delete: true
         QCK.Kingdom.promote: true
         QCK.Kingdom.claim: true
   QCK.Kingdom.info:
      description: Allows a player the ability to get information on a kingdom.
      default: false
   QCK.Kingdom.create:
      description: Allows a player the ability to create a kingdom.
      default: false
   QCK.Kingdom.delete:
      description: Allows a king the ability to delete their kingdom.
      default: false
   QCK.Kingdom.promote:
      description: Allows a king the ability to promote someone in their kingdom.
      default: false
   QCK.Kingdom.claim:
      description: Allows a king the ability to claim land for their kingdom.
      default: false